use crate::models::TRACK_COUNT;

pub const TRACK_SIDEBAR_WIDTH: f32 = 420.0;

pub const PATTERN_LABEL_GUTTER: f32 = 132.0;
pub const PATTERN_TOP_RULER: f32 = 38.0;
pub const PATTERN_ROW_HEIGHT: f32 = 38.0;
pub const PATTERN_GRID_PADDING: f32 = 12.0;
pub const PATTERN_PANEL_RADIUS: f32 = 7.0;
pub const PATTERN_LABEL_INSET: f32 = 12.0;

pub const PATTERN_GHOST_MARKER_WIDTH_FACTOR: f32 = 0.42;
pub const PATTERN_FILL_MARKER_WIDTH_FACTOR: f32 = 0.74;
pub const PATTERN_DEFAULT_MARKER_WIDTH_FACTOR: f32 = 0.68;
pub const PATTERN_GHOST_MARKER_HEIGHT: f32 = 8.0;
pub const PATTERN_FILL_MARKER_HEIGHT: f32 = 18.0;
pub const PATTERN_DEFAULT_MARKER_HEIGHT: f32 = 15.0;
pub const PATTERN_MIN_MARKER_WIDTH: f32 = 2.0;
pub const PATTERN_MIN_ACCENT_MARKER_WIDTH: f32 = 2.5;
pub const PATTERN_MAX_SMALL_MARKER_WIDTH: f32 = 8.0;
pub const PATTERN_MAX_MARKER_WIDTH: f32 = 11.0;
pub const PATTERN_MAX_ACCENT_MARKER_WIDTH: f32 = 12.0;

pub const PATTERN_MIN_GRID_HEIGHT: f32 =
    PATTERN_TOP_RULER + PATTERN_ROW_HEIGHT * TRACK_COUNT as f32 + PATTERN_GRID_PADDING * 2.0;
